import {
  BASIC_ROCK_EVENTS,
  DISCO_FLOOR_EVENTS,
  KICK_SNARE_EVENTS,
  RIDE_GROOVE_EVENTS,
  SIMPLE_SAMBA_EVENTS,
  STAB_RIFF_EVENTS,
  TOM_FILL_EVENTS,
} from './patterns';
import {
  AMEN_KIRIGI_EVENTS,
  BENDIR_DEM_EVENTS,
  BREAKBEAT_EVENTS,
  CIFTETELLI_EVENTS,
  DEF_SIKIRTISI_EVENTS,
  DUM_TEKA_EVENTS,
  DUM_TEK_TEMELI_EVENTS,
  FUNK_16_EVENTS,
  HALAY_EVENTS,
  HIPHOP_90_EVENTS,
  KASIK_9_8_EVENTS,
  REGGAETON_EVENTS,
  ROMAN_9_8_EVENTS,
  SWING_SHUFFLE_EVENTS,
  TRAP_ROLL_EVENTS,
  YARIM_BAR_FILL_EVENTS,
} from './patternsExtra';
import type { PadSongDefinition } from './types';

/**
 * Instructional rhythm lessons, not songs. Ordered as a rough curriculum:
 * Turkish usûls first (they auto-switch to the Turkish bank), then modern
 * grooves on the drums bank, easiest to hardest within each group.
 */
export const PAD_SONGS: PadSongDefinition[] = [
  // --- Türk usûlleri (turkish bank) ---
  {
    id: 'pad-dum-tek',
    title: 'Düm-Tek Temeli',
    difficulty: 'easy',
    events: DUM_TEK_TEMELI_EVENTS,
    partialCount: 4,
    bankId: 'turkish',
  },
  {
    id: 'pad-dum-teka',
    title: 'Düm-Teka',
    difficulty: 'easy',
    events: DUM_TEKA_EVENTS,
    partialCount: 6,
    bankId: 'turkish',
  },
  {
    id: 'pad-bendir-dem',
    title: 'Bendir Dem',
    difficulty: 'easy',
    events: BENDIR_DEM_EVENTS,
    partialCount: 3,
    bankId: 'turkish',
  },
  {
    id: 'pad-ciftetelli',
    title: 'Çiftetelli',
    difficulty: 'medium',
    events: CIFTETELLI_EVENTS,
    partialCount: 6,
    bankId: 'turkish',
  },
  {
    id: 'pad-halay',
    title: 'Halay',
    difficulty: 'medium',
    events: HALAY_EVENTS,
    partialCount: 6,
    bankId: 'turkish',
  },
  {
    id: 'pad-def-sikirtisi',
    title: 'Def Şıkırtısı',
    difficulty: 'medium',
    events: DEF_SIKIRTISI_EVENTS,
    partialCount: 8,
    bankId: 'turkish',
  },
  {
    id: 'pad-roman-9-8',
    title: 'Roman Havası 9/8',
    difficulty: 'hard',
    events: ROMAN_9_8_EVENTS,
    partialCount: 5,
    bankId: 'turkish',
  },
  {
    id: 'pad-kasik-9-8',
    title: 'Kaşık 9/8',
    difficulty: 'hard',
    events: KASIK_9_8_EVENTS,
    partialCount: 8,
    bankId: 'turkish',
  },
  // --- Modern groove'lar (drums bank) ---
  {
    id: 'pad-kick-snare',
    title: 'Kick & Snare',
    difficulty: 'easy',
    events: KICK_SNARE_EVENTS,
    partialCount: 5,
    bankId: 'drums',
  },
  {
    id: 'pad-basic-rock',
    title: 'Basic Rock',
    difficulty: 'easy',
    events: BASIC_ROCK_EVENTS,
    partialCount: 16,
    bankId: 'drums',
  },
  {
    id: 'pad-hiphop-90',
    title: 'Hip-Hop 90',
    difficulty: 'easy',
    events: HIPHOP_90_EVENTS,
    partialCount: 13,
    bankId: 'drums',
  },
  {
    id: 'pad-disco-floor',
    title: 'Disco Floor',
    difficulty: 'medium',
    events: DISCO_FLOOR_EVENTS,
    partialCount: 12,
    bankId: 'drums',
  },
  {
    id: 'pad-reggaeton',
    title: 'Reggaeton',
    difficulty: 'medium',
    events: REGGAETON_EVENTS,
    partialCount: 8,
    bankId: 'drums',
  },
  {
    id: 'pad-trap-roll',
    title: 'Trap Roll',
    difficulty: 'medium',
    events: TRAP_ROLL_EVENTS,
    partialCount: 12,
    bankId: 'drums',
  },
  {
    id: 'pad-swing-shuffle',
    title: 'Swing Shuffle',
    difficulty: 'medium',
    events: SWING_SHUFFLE_EVENTS,
    partialCount: 12,
    bankId: 'drums',
  },
  {
    id: 'pad-tom-fill',
    title: 'Tom Fill',
    difficulty: 'medium',
    events: TOM_FILL_EVENTS,
    partialCount: 6,
    bankId: 'drums',
  },
  {
    id: 'pad-yarim-bar-fill',
    title: 'Yarım Bar Fill',
    difficulty: 'medium',
    events: YARIM_BAR_FILL_EVENTS,
    partialCount: 12,
    bankId: 'drums',
  },
  {
    id: 'pad-ride-groove',
    title: 'Ride Groove',
    difficulty: 'medium',
    events: RIDE_GROOVE_EVENTS,
    partialCount: 16,
    bankId: 'drums',
  },
  {
    id: 'pad-stab-riff',
    title: 'Stab Riff',
    difficulty: 'medium',
    events: STAB_RIFF_EVENTS,
    partialCount: 10,
    bankId: 'drums',
  },
  {
    id: 'pad-funk-16',
    title: "Funk 16'lık",
    difficulty: 'hard',
    events: FUNK_16_EVENTS,
    partialCount: 8,
    bankId: 'drums',
  },
  {
    id: 'pad-breakbeat',
    title: 'Breakbeat',
    difficulty: 'hard',
    events: BREAKBEAT_EVENTS,
    partialCount: 13,
    bankId: 'drums',
  },
  {
    id: 'pad-simple-samba',
    title: 'Simple Samba',
    difficulty: 'hard',
    events: SIMPLE_SAMBA_EVENTS,
    partialCount: 14,
    bankId: 'drums',
  },
  {
    id: 'pad-amen-kirigi',
    title: 'Amen Kırığı',
    difficulty: 'hard',
    events: AMEN_KIRIGI_EVENTS,
    partialCount: 15,
    bankId: 'drums',
  },
];

export const PAD_SONG_CATALOG = PAD_SONGS;

export function getPadSongById(id: string): PadSongDefinition | undefined {
  return PAD_SONGS.find((song) => song.id === id);
}
