/**
 * Billie Jean play-along chart from PianoMusique.ch / Delvecchio sheet
 * (F#m, q=114, 4/4). Monophonic, C4–B5 (enharmonic Gb/Db).
 *
 * Full form follows the PDF:
 *   Intro bass → Strings/groove → Verse (F#m + Bm) → Chorus hook →
 *   Verse 2 → Chorus → Keyboard (D/F#m) → Chorus outro
 *
 * Run: node scripts/buildBillieJeanEvents.js
 */
const fs = require('fs');

const BPM = 114;
const Q = Math.round(60_000 / BPM); // ≈ 526
const E = Math.round(Q / 2); // ≈ 263
const H = Q * 2;

/** @type {{ noteId: string, atMs: number }[]} */
const events = [];
let t = 0;

/** @param {string} noteId @param {number} durMs */
function n(noteId, durMs = E) {
  events.push({ noteId, atMs: t });
  t += durMs;
}

function rest(durMs) {
  t += durMs;
}

/** Iconic F#m bass (PDF LH), up an octave+ into C4–B5: Gb Db E Gb | E Db B Db */
function bassFsm(bars = 1) {
  const pat = ['Gb4', 'Db4', 'E4', 'Gb4', 'E4', 'Db4', 'B4', 'Db4'];
  for (let b = 0; b < bars; b++) {
    for (const note of pat) n(note, E);
  }
}

/** Bm7 answer bass (PDF bars 15–16 / 19–20): B Gb A B | A Gb E Gb */
function bassBm(bars = 1) {
  const pat = ['B4', 'Gb4', 'A4', 'B4', 'A4', 'Gb4', 'E4', 'Gb4'];
  for (let b = 0; b < bars; b++) {
    for (const note of pat) n(note, E);
  }
}

/**
 * Chorus vocal hook — "Billie Jean is not my lover…"
 * (playable sketch over the groove; not in the bass clef of the PDF).
 */
function chorus() {
  n('Gb4', Q);
  n('A4', Q);
  n('B4', Q);
  n('Db5', Q);
  n('B4', Q);
  n('A4', Q);
  n('Gb4', Q);
  n('E4', Q);
  n('Gb4', Q);
  n('A4', Q);
  n('B4', Q);
  n('Db5', Q);
  n('E5', Q);
  n('Db5', Q);
  n('B4', Q);
  n('A4', Q);
  n('B4', Q);
  n('A4', Q);
  n('Gb4', Q);
  n('E4', Q);
  n('Db4', Q);
  n('E4', Q);
  n('Gb4', Q);
  rest(Q);
  n('A4', Q);
  n('B4', Q);
  n('Db5', Q);
  n('E5', Q);
  n('Db5', Q);
  n('B4', Q);
  n('A4', Q);
  n('Gb4', Q);
}

/**
 * PDF page 2 "Keyboards" (bars 23–30) — D ↔ F#m climb / synth line.
 */
function keyboards() {
  for (let i = 0; i < 2; i++) {
    // D feel
    n('D5', Q);
    n('Db5', Q);
    n('B4', Q);
    n('A4', Q);
    n('Gb4', Q);
    n('A4', Q);
    n('B4', Q);
    n('Db5', Q);
    // F#m feel
    n('D5', Q);
    n('E5', Q);
    n('Gb5', Q);
    n('E5', Q);
    n('Db5', Q);
    n('B4', Q);
    n('A4', Q);
    n('Gb4', Q);
  }
  // C#7 lead-in ("To Verse and Chorus") — accented G# → resolve
  for (let i = 0; i < 8; i++) n('Ab4', E); // G# → Ab
  n('Db5', H);
  n('Db4', H);
}

// ── Full chart (PDF form) ──────────────────────────────────
// Bars 1–2 drums skipped (silence not useful for play-along).

// Intro bass (PDF 3–6)
bassFsm(4);

// Strings / groove continues (PDF 7–10)
bassFsm(4);

// Verse and chorus groove (PDF 11–18): F#m ×4, Bm ×2, F#m ×2
bassFsm(4);
bassBm(2);
bassFsm(2);

// Vocal chorus hook (recognizable)
chorus();

// Groove again + Bm first ending feel (PDF 19–22)
bassFsm(2);
bassBm(2);
bassFsm(2);

// Second chorus
chorus();

// Keyboards section (PDF 23–30)
keyboards();

// Outro: groove + final chorus
bassFsm(2);
chorus();
bassFsm(2);

const body = events
  .map((e) => `  { noteId: '${e.noteId}', atMs: ${e.atMs} },`)
  .join('\n');

const out = `import type { NoteId } from '../pianoNotes';

/**
 * Billie Jean — full piano chart for Öğretici Modu.
 * Source: PianoMusique.ch / Davide Delvecchio (F#m, q=114).
 * Bass groove + chorus vocal hook + keyboard section (monophonic, C4–B5).
 * Generated by scripts/buildBillieJeanEvents.js — do not hand-edit.
 */
export const BILLIE_JEAN_EVENTS: { noteId: NoteId; atMs: number }[] = [
${body}
];
`;

fs.writeFileSync('src/instruments/piano/songs/billieJeanEvents.ts', out);

const last = events[events.length - 1];
console.log(
  JSON.stringify({
    notes: events.length,
    durationSec: +(last.atMs / 1000).toFixed(1),
    quarterMs: Q,
    // Find first chorus start: after 4+4+4+2+2 = 16 bars of bass = 16*8 = 128 notes
  }),
);

// Indices for partial (~50 notes): first vocal chorus
let chorusStart = -1;
for (let i = 0; i < events.length - 3; i++) {
  if (
    events[i].noteId === 'Gb4' &&
    events[i + 1].noteId === 'A4' &&
    events[i + 2].noteId === 'B4' &&
    events[i + 3].noteId === 'Db5' &&
    // chorus uses quarters — gap between Gb and A should be ~Q
    events[i + 1].atMs - events[i].atMs >= Q - 5
  ) {
    chorusStart = i;
    break;
  }
}
const partialCount = 50;
console.log(
  JSON.stringify({
    chorusStartIndex: chorusStart,
    partialEndIndex: chorusStart + partialCount - 1,
    partialFirst: events[chorusStart],
    partialLast: events[chorusStart + partialCount - 1],
  }),
);
